### ISSUE TITLE
Error: Execution failed for task ':app:ndkBuild'.

### ISSUE THREAD

**Issue by itvignes09** [KePeng1019/SmartPaperScan#1]
When I try to run this project it shows following error. I can not run it

> Error:Execution failed for task ':app:ndkBuild'.
A problem occurred starting process 'command '/media/vignes/Softwares/Ubuntu/Android/SDK/ndk-bundle/ndk-build.cmd''

**Comment by KePeng1019** [comment]
it seems cause by ndk, you may check your ndk tools.
