### ISSUE TITLE
How do I set to only detect rectangles, skip any other geometry

### ISSUE THREAD

**Issue by maiksonstrife** [KePeng1019/SmartPaperScan#12]
I need to only detect rectangles.
Another thing the would be useful is reduce the detection speed, sometimes I do detect but with a tiny move the detection update to another one.

 Can you please help me if possible ?

**Comment by KePeng1019** [comment]
I think the detecting not working well on complex environment, but i'd be happy to help if you could provide a sample image.

**Comment by maiksonstrife** [comment]
when taking photo the lines tends to find a shape between points, sometimes it finds a triangle because only finds 3 points.

 I would like to always look for 4 points and return a rectangle or square, even if only finds a triangle, when taking a photo, gives a default for 4 points and a rectangle.

![image](https://user-images.githubusercontent.com/32269310/69821652-0a85a300-11e3-11ea-9d54-5646f5eb9bfc.png)

**Comment by KePeng1019** [comment]
got it. i will try to fix it when i am free.

**Comment by maiksonstrife** [comment]
Thanks, Thanks for the quick response too !!

**Comment by maiksonstrife** [comment]
I've made it, when detects a triangle, then return default rectangle, just added one line of code, your code handled it

![image](https://user-images.githubusercontent.com/32269310/69880186-19825900-12a8-11ea-9fdf-832a9266be00.png)

**Comment by KePeng1019** [comment]
Great!

**Comment by tiagosito** [comment]
This pull request that I am sending is to improve detection and also to prevent a triangle from being generated when detecting an object.
I know that the triangle generation fix was closed in [issue 12](https://github.com/KePeng1019/SmartPaperScan/issues/12#issuecomment-559837496), but what it seemed when running the app is that this problem still remained.

Thanks for the shared content!
