### ISSUE TITLE
Still have a triangle after take the photo

### ISSUE THREAD

**Issue by francescogatto** [KePeng1019/SmartPaperScan#16]
With the preview I have a perfect rectangle, after the shot i have a triangle. 

thanks

**Comment by francescogatto** [comment]
I'm trying with Italian identity card like this: https://images.app.goo.gl/tq85YakrRXGZnvHP6

**Comment by KePeng1019** [comment]
i will try to fix it.

**Comment by KePeng1019** [comment]
i take latest preview pic as the result if taken pic can not detect rectangle. I think it resolve your problem.
