### ISSUE TITLE
可以弄一个检测任何物品的吗 不一定非要是文档

### ISSUE THREAD

**Issue by yushilong** [KePeng1019/SmartPaperScan#2]
可以弄一个检测任何物品的吗 不一定非要是文档

**Comment by KePeng1019** [comment]
可以检测矩形的物品，卡片身份证等都是可以的

**Comment by yushilong** [comment]
@KePeng1019 能不能支持一下检测鞋子，衣服等等

**Comment by KePeng1019** [comment]
@yushilong 你可以试试tensorflow，https://github.com/tensorflow/tensorflow。有安卓版本的apk，支持检测任何物品。这个项目用到的是简单的opencv，模型做的比较简单，支持检测任意物品目前做不到

**Comment by KePeng1019** [comment]
@yushilong 这个项目用的是opencv，算法模型比较简单，支持任意物品的检测比较困难。你可以 试试 tensorflow，有安卓版本的apk，支持检测任意物品。https://github.com/tensorflow/tensorflow

**Comment by yushilong** [comment]
@KePeng1019 好的，谢谢
